// <auto-generated />
using System;
using ExamBurcu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamBurcu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210150101_InitialCodeFirstMigration")]
    partial class InitialCodeFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamBurcu.Data.child", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("namesurname")
                        .HasMaxLength(80)
                        .HasColumnType("character varying");

                    b.Property<long>("tckn")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("child_pk");

                    b.HasIndex("tckn")
                        .IsUnique();

                    b.HasIndex(new[] { "tckn" }, "child_unique")
                        .IsUnique();

                    b.ToTable("child", (string)null);
                });

            modelBuilder.Entity("ExamBurcu.Data.doctor", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("namesurname")
                        .HasMaxLength(80)
                        .HasColumnType("character varying");

                    b.Property<long>("tckn")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("doctor_pk");

                    b.HasIndex("tckn")
                        .IsUnique();

                    b.HasIndex(new[] { "tckn" }, "doctor_unique")
                        .IsUnique();

                    b.ToTable("doctor", (string)null);
                });

            modelBuilder.Entity("ExamBurcu.Data.vaccine", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying");

                    b.Property<int?>("stockcount")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("vaccine_pk");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex(new[] { "code" }, "vaccine_unique")
                        .IsUnique();

                    b.ToTable("vaccine", (string)null);
                });

            modelBuilder.Entity("ExamBurcu.Data.vaccineapplication", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("applicationtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("childid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<long?>("doctorid")
                        .HasColumnType("bigint");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("vaccineid")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("vaccineapplication_pk");

                    b.HasIndex("childid");

                    b.HasIndex("doctorid");

                    b.HasIndex("vaccineid");

                    b.ToTable("vaccineapplication", (string)null);
                });

            modelBuilder.Entity("ExamBurcu.Data.vaccineschedule", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<short?>("month")
                        .HasColumnType("smallint");

                    b.Property<long?>("vaccineid")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("vaccineschedule_pk");

                    b.HasIndex("month", "vaccineid")
                        .IsUnique();

                    b.HasIndex(new[] { "vaccineid", "month" }, "vaccineschedule_unique")
                        .IsUnique();

                    b.ToTable("vaccineschedule", (string)null);
                });

            modelBuilder.Entity("ExamBurcu.Data.vaccineapplication", b =>
                {
                    b.HasOne("ExamBurcu.Data.child", "child")
                        .WithMany("vaccineapplications")
                        .HasForeignKey("childid")
                        .HasConstraintName("vaccineapplication_child_fk");

                    b.HasOne("ExamBurcu.Data.doctor", "doctor")
                        .WithMany("vaccineapplications")
                        .HasForeignKey("doctorid")
                        .HasConstraintName("vaccineapplication_doctor_fk");

                    b.HasOne("ExamBurcu.Data.vaccine", "vaccine")
                        .WithMany("vaccineapplications")
                        .HasForeignKey("vaccineid")
                        .HasConstraintName("vaccineapplication_vaccine_fk");

                    b.Navigation("child");

                    b.Navigation("doctor");

                    b.Navigation("vaccine");
                });

            modelBuilder.Entity("ExamBurcu.Data.vaccineschedule", b =>
                {
                    b.HasOne("ExamBurcu.Data.vaccine", "vaccine")
                        .WithMany("vaccineschedules")
                        .HasForeignKey("vaccineid")
                        .HasConstraintName("vaccineschedule_vaccine_fk");

                    b.Navigation("vaccine");
                });

            modelBuilder.Entity("ExamBurcu.Data.child", b =>
                {
                    b.Navigation("vaccineapplications");
                });

            modelBuilder.Entity("ExamBurcu.Data.doctor", b =>
                {
                    b.Navigation("vaccineapplications");
                });

            modelBuilder.Entity("ExamBurcu.Data.vaccine", b =>
                {
                    b.Navigation("vaccineapplications");

                    b.Navigation("vaccineschedules");
                });
#pragma warning restore 612, 618
        }
    }
}
